// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALTn7wgO3LDgXovTKEG_ffdlUdyPg5Wc',
    appId: '1:20436029541:web:6bfcb93a0f6fbdebd9f68c',
    messagingSenderId: '20436029541',
    projectId: 'chameleongame-2214d',
    authDomain: 'chameleongame-2214d.firebaseapp.com',
    storageBucket: 'chameleongame-2214d.firebasestorage.app',
    measurementId: 'G-2L3NMPB9SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUPnO_MVX2uQkxcygv_-0npYwZFoyC3OI',
    appId: '1:20436029541:android:f31264c765f68b30d9f68c',
    messagingSenderId: '20436029541',
    projectId: 'chameleongame-2214d',
    storageBucket: 'chameleongame-2214d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgPVDRH8GGqi4AglQqTMLPr2OxAG8gS_E',
    appId: '1:20436029541:ios:cb10ca55bd3dbbc0d9f68c',
    messagingSenderId: '20436029541',
    projectId: 'chameleongame-2214d',
    storageBucket: 'chameleongame-2214d.firebasestorage.app',
    iosBundleId: 'com.example.project4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgPVDRH8GGqi4AglQqTMLPr2OxAG8gS_E',
    appId: '1:20436029541:ios:cb10ca55bd3dbbc0d9f68c',
    messagingSenderId: '20436029541',
    projectId: 'chameleongame-2214d',
    storageBucket: 'chameleongame-2214d.firebasestorage.app',
    iosBundleId: 'com.example.project4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDALTn7wgO3LDgXovTKEG_ffdlUdyPg5Wc',
    appId: '1:20436029541:web:c9cc8dc22580ef14d9f68c',
    messagingSenderId: '20436029541',
    projectId: 'chameleongame-2214d',
    authDomain: 'chameleongame-2214d.firebaseapp.com',
    storageBucket: 'chameleongame-2214d.firebasestorage.app',
    measurementId: 'G-V5Y8QLTZQR',
  );
}
